apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: microservicios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: docker.io/rojassluu/gateway-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          # Si tu gateway necesita hablar con otros servicios:
          env:
            - name: USUARIOS_URL
              value: http://usuarios.microservicios.svc.cluster.local:8080
            - name: PEDIDOS_URL
              value: http://pedidos.microservicios.svc.cluster.local:8080

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: microservicios
spec:
  selector:
    app: gateway
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: NodePort
