apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedidos
  namespace: microservicios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pedidos
  template:
    metadata:
      labels:
        app: pedidos
    spec:
      containers:
        - name: pedidos
          image: docker.io/rojassluu/pedidos-service:latest   # Imagen en Docker Hub
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            # Si el servicio de pedidos depende de otros, define aquí las URLs internas:
            # - name: USUARIOS_URL
            #   value: http://usuarios.microservicios.svc.cluster.local:8080
---
apiVersion: v1
kind: Service
metadata:
  name: pedidos
  namespace: microservicios
spec:
  selector:
    app: pedidos
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
