server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: usuarios-service
          uri: http://usuarios:8081
          predicates:
            - Path=/api/usuarios/**
        - id: pedidos-service
          uri: http://pedidos:8080
          predicates:
            - Path=/api/pedidos/**
